### ISSUE TITLE
Install on mac

### ISSUE THREAD

**Issue by zhuzh1983** [UNLV-SPFG/UNLV-SPFG.github.io#2]
If you have a mac and had successfully run the website, could you paste your command lines?

**Comment by zhuzh1983** [comment]
Fixed.
First: follow https://jekyllrb.com/docs/installation/macos/ 
Second: delete bundler if you have installed it using a different ruby. >gem uninstall bundler
Third: reinstall bundler following the instruction. If you have issues with nokogiri, just >gem uninstall nokogiri before install bundler. The bundler will fetch the correct nokogiri

**Comment by zhangsj96** [comment]
```
shjzhang@Shangjias-MacBook-Pro UNLV-SPFG.github.io % bundle exec jekyll serve                 
Configuration file: /Users/shjzhang/github/UNLV-SPFG.github.io/_config.yml
            Source: /Users/shjzhang/github/UNLV-SPFG.github.io
       Destination: /Users/shjzhang/github/UNLV-SPFG.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme mmistakes/minimal-mistakes
       Jekyll Feed: Generating feed for posts
                    done in 9.919 seconds.
 Auto-regeneration: enabled for '/Users/shjzhang/github/UNLV-SPFG.github.io'
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.0.0/bin/jekyll)
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `require_relative'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `setup'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:102:in `process'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:25:in `<top (required)>'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/shjzhang/.gem/ruby/3.0.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:23:in `load'
	from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
```
I have this error after running 

> bundle exec jekyll serve        

I followed https://stackoverflow.com/questions/65989040/bundle-exec-jekyll-serve-cannot-load-such-file and solved the problem. or this one https://github.com/jekyll/jekyll/issues/8523

Maybe later on the Gemfile should be updated to include
gem "webrick"
or 
bundle add webrick

**Comment by sabaronett** [comment]
Reopening issue until READMEs are updated with info from @zhangsj96's most [recent comment](https://github.com/UNLV-SPFG/UNLV-SPFG.github.io/issues/2#issuecomment-1021902508).

**Comment by sabaronett** [comment]
Closing with commit 2884c3d995c6e709140567d4daa14f791be4961a.

Thanks for the suggestion, @zhangsj96!
